package pts.adf.summit.model.views;

import oracle.jbo.server.ViewObjectImpl;

import pts.adf.summit.model.views.common.SEmpView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 14 14:47:11 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SEmpViewImpl extends ViewObjectImpl implements SEmpView {
    /**
     * This is the default constructor (do not remove).
     */
    public SEmpViewImpl() {
    }

    /**
     * Returns the variable value for SalesIdBindVar.
     * @return variable value for SalesIdBindVar
     */
    public Integer getSalesIdBindVar() {
        return (Integer) ensureVariableManager().getVariableValue("SalesIdBindVar");
    }

    /**
     * Sets <code>value</code> for variable SalesIdBindVar.
     * @param value value to bind as SalesIdBindVar
     */
    public void setSalesIdBindVar(Integer value) {
        ensureVariableManager().setVariableValue("SalesIdBindVar", value);
    }

    /**
     * Returns the variable value for TitleIdBindVar.
     * @return variable value for TitleIdBindVar
     */
    public Integer getTitleIdBindVar() {
        return (Integer) ensureVariableManager().getVariableValue("TitleIdBindVar");
    }

    /**
     * Sets <code>value</code> for variable TitleIdBindVar.
     * @param value value to bind as TitleIdBindVar
     */
    public void setTitleIdBindVar(Integer value) {
        ensureVariableManager().setVariableValue("TitleIdBindVar", value);
    }
}

