package pts.adf.summit.model.views;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.util.Date;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 14 11:46:35 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SOrdViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_SORD = 0;
    public static final int ENTITY_SCUSTOMER = 1;
    public static final int ENTITY_SEMP = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        CustomerId,
        DateOrdered,
        DateShipped,
        SalesRepId,
        Total,
        PaymentTypeId,
        PaymentOptionId,
        OrderFilled,
        SalesRepLastName,
        Id1,
        CustomerName,
        Id2,
        TimeToShip,
        SItemView,
        SEmpView1,
        SPaymentTypeView1,
        YesNoView1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int DATEORDERED = AttributesEnum.DateOrdered.index();
    public static final int DATESHIPPED = AttributesEnum.DateShipped.index();
    public static final int SALESREPID = AttributesEnum.SalesRepId.index();
    public static final int TOTAL = AttributesEnum.Total.index();
    public static final int PAYMENTTYPEID = AttributesEnum.PaymentTypeId.index();
    public static final int PAYMENTOPTIONID = AttributesEnum.PaymentOptionId.index();
    public static final int ORDERFILLED = AttributesEnum.OrderFilled.index();
    public static final int SALESREPLASTNAME = AttributesEnum.SalesRepLastName.index();
    public static final int ID1 = AttributesEnum.Id1.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int ID2 = AttributesEnum.Id2.index();
    public static final int TIMETOSHIP = AttributesEnum.TimeToShip.index();
    public static final int SITEMVIEW = AttributesEnum.SItemView.index();
    public static final int SEMPVIEW1 = AttributesEnum.SEmpView1.index();
    public static final int SPAYMENTTYPEVIEW1 = AttributesEnum.SPaymentTypeView1.index();
    public static final int YESNOVIEW1 = AttributesEnum.YesNoView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SOrdViewRowImpl() {
    }
    
    public oracle.jbo.domain.Number calculateTimeToShip(Date ordered, Date shipped) {

        if (null != shipped) {
            long days = (shipped.getTime() - ordered.getTime()) / (1000 * 60 * 60 * 24);
            return new Number(days);
        } else
            return new Number(0);
    }

}

