package pts.adf.summit.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 14 14:47:31 EEST 2015
// ---------------------------------------------------------------------
public interface SEmpView extends ViewObject {
    void setSalesIdBindVar(Integer value);
}

