package pts.adf.summit.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 14 15:03:18 EEST 2015
// ---------------------------------------------------------------------
public interface SItemViewRow extends Row {
    void deleteOrderItem();
}

